### ISSUE TITLE
why #define PY_SSIZE_T_CLEAN?

### ISSUE THREAD

**Issue by tdhock** [deltarod/PeakError#2]
hey @deltarod in https://github.com/deltarod/PeakError/blob/master/src/interface.c I see
```c
#define PY_SSIZE_T_CLEAN
```
which is documented https://www.python.org/dev/peps/pep-0353/ as affecting the output of PyArg_ParseTuple with conversion codes `s#` and `t#` but I don't see any usage of those codes. Can you please explain what this is doing?

**Comment by deltarod** [comment]
Probably a bit to zealous on the copy/paste from some examples. I found one example [here](https://numpy.org/devdocs/user/c-info.ufunc-tutorial.html) which has it fairly undocumented.

**Comment by tdhock** [comment]
ok thanks
