### ISSUE TITLE
why passing *_count variables as arguments in C extension module?

### ISSUE THREAD

**Issue by tdhock** [deltarod/PeakError#3]
Hi @deltarod in https://github.com/deltarod/PeakError/blob/master/src/interface.c I see
```c
static PyObject *
PeakErrorInterface(PyObject *self, PyObject *args)
{
    PyArrayObject *peak_start, *peak_end, *region_start, *region_end, *region_ann;
    int *peak_count, *region_count;
    if(!PyArg_ParseTuple(args, "O!O!iO!O!O!i",
                         &PyArray_Type, &peak_start,
                         &PyArray_Type, &peak_end,
                         &peak_count,
                         &PyArray_Type, &region_start,
                         &PyArray_Type, &region_end,
                         &PyArray_Type, &region_ann,
                         &region_count))
```
The peak_count/region_count arguments seem un-necessary, since they can be derived from the size of the numpy arrays, did you know? I'm just wondering if there is any reason that you did not use PyArray_SIZE? or PyArray_DIM, which I used here https://r-forge.r-project.org/scm/viewvc.php/python/SegAnnot_interface.c?view=markup&revision=29&root=segannot 

in PeakError I think you could do
```c
*peak_count = PyArray_DIM(peak_start,0);
```

**Comment by deltarod** [comment]
I'm not quite sure, I remember facing some frustrations with these particular parts but I cant quite remember why anymore.

**Comment by tdhock** [comment]
ok thanks
